#!/usr/bin/env bash
# user dragons the userbot
# (C) Copyright 2021 TeamDragons
# All rights reserved
#
# Worker Bash Run


_get_ziplink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO == "dragons" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0NvZGV4L0NvZGV4L2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    elif [[ $UPSTREAM_REPO == "dragons" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RlYW1EcmFnb25zL0RyYWdvbnMtVXNlcmJvdC9hcmNoaXZlL21haW4uemlw" | base64 -d
    elif [[ $UPSTREAM_REPO =~ $regex ]]
    then
        if [[ $UPSTREAM_REPO_BRANCH ]]
        then
            echo "${UPSTREAM_REPO}/archive/${UPSTREAM_REPO_BRANCH}.zip"
        else
            echo "${UPSTREAM_REPO}/archive/main.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL0NvZGV4L0NvZGV4L2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    fi
}

_get_repolink () {
    local regex
    local rlink
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO == "dragons" ]]
    then
        rlink=`echo "aHR0cHM6Ly9naXRodWIuY29tL1RlYW1EcmFnb25zL0RyYWdvbnMtVXNlcmJvdA==" | base64 -d`
    elif [[ $UPSTREAM_REPO =~ $regex ]]
    then
        rlink=`echo "${UPSTREAM_REPO}"`
    else
        rlink=`echo "aHR0cHM6Ly9naXRodWIuY29tL1RlYW1EcmFnb25zL0RyYWdvbnMtVXNlcmJvdA==" | base64 -d`
    fi
    echo "$rlink"
}


_run_python_code() {
    python3${pVer%.*} -c "$1"
}

_run_dragons_git() {
    $(_run_python_code 'from git import Repo
import sys
OFFICIAL_UPSTREAM_REPO = "https://github.com/TeamDragons/Dragons-Userbot"
ACTIVE_BRANCH_NAME = "main"
repo = Repo.init()
origin = repo.create_remote("temponame", OFFICIAL_UPSTREAM_REPO)
origin.fetch()
repo.create_head(ACTIVE_BRANCH_NAME, origin.refs[ACTIVE_BRANCH_NAME])
repo.heads[ACTIVE_BRANCH_NAME].checkout(True) ')
}

_run_drg_git() {
    local repolink=$(_get_repolink)
    $(_run_python_code 'from git import Repo
import sys
OFFICIAL_UPSTREAM_REPO="'$repolink'"
ACTIVE_BRANCH_NAME = "'$UPSTREAM_REPO_BRANCH'" or "main"
repo = Repo.init()
origin = repo.create_remote("temponame", OFFICIAL_UPSTREAM_REPO)
origin.fetch()
repo.create_head(ACTIVE_BRANCH_NAME, origin.refs[ACTIVE_BRANCH_NAME])
repo.heads[ACTIVE_BRANCH_NAME].checkout(True) ')
}

_set_bot () {
    local zippath
    zippath="Dragons-Userbot.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_ziplink) -O "$zippath"
    echo "  Unpacking Data ..."
    DRGPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    _run_dragons_git
    cd $DRGPATH
    _run_drg_git
    python3 ../setup/updater.py ../requirements.txt requirements.txt
    chmod -R 755 bin
    echo "    Starting DragonsUserbot    "
    echo "
                    ██████╗░██████╗░░█████╗░░██████╗░░█████╗░███╗░░██╗
                    ██╔══██╗██╔══██╗██╔══██╗██╔════╝░██╔══██╗████╗░██║
                    ██║░░██║██████╔╝███████║██║░░██╗░██║░░██║██╔██╗██║
                    ██║░░██║██╔══██╗██╔══██║██║░░╚██╗██║░░██║██║╚████║
                    ██████╔╝██║░░██║██║░░██║╚██████╔╝╚█████╔╝██║░╚███║
                    ╚═════╝░╚═╝░░╚═╝╚═╝░░╚═╝░╚═════╝░░╚════╝░╚═╝░░╚══╝
    "
    echo "
           ██╗░░░██╗░██████╗███████╗██████╗░██████╗░░█████╗░████████╗
           ██║░░░██║██╔════╝██╔════╝██╔══██╗██╔══██╗██╔══██╗╚══██╔══╝
           ██║░░░██║╚█████╗░█████╗░░██████╔╝██████╦╝██║░░██║░░░██║░░░
           ██║░░░██║░╚═══██╗██╔══╝░░██╔══██╗██╔══██╗██║░░██║░░░██║░░░
           ╚██████╔╝██████╔╝███████╗██║░░██║██████╦╝╚█████╔╝░░░██║░░░
           ░╚═════╝░╚═════╝░╚══════╝╚═╝░░╚═╝╚═════╝░░╚════╝░░░░╚═╝░░░
    "
    python3 -m dragons
}

_set_bot
